# Generated by Django 5.1.1 on 2024-10-15 22:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0003_author_alter_album_options_remove_album_artist_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='albums', to='albums.author'),
        ),
    ]
