# Generated by Django 5.1.1 on 2024-10-15 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0004_alter_album_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
    ]
