# Generated by Django 5.1.1 on 2024-10-17 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0006_genre_user_album_genres_album_purchased_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='purchased_by',
            new_name='users',
        ),
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название жанра'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Электронная почта'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=100, verbose_name='Имя пользователя'),
        ),
    ]
