# Generated by Django 5.1.1 on 2024-10-17 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0007_rename_purchased_by_album_users_alter_genre_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default=12345678, max_length=100, verbose_name='Пароль'),
            preserve_default=False,
        ),
    ]
