# Generated by Django 5.1.1 on 2024-11-27 10:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0010_alter_user_email_alter_user_password_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AlterField(
            model_name='album',
            name='users',
            field=models.ManyToManyField(related_name='purchased_albums', to=settings.AUTH_USER_MODEL, verbose_name='Пользователи'),
        ),
    ]
